name: React CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test React App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test -- --watchAll=false

      - name: Build Application
        run: npm run build

      - name: Lint and Security Check
        run: |
          npm run lint
          npm audit --audit-level=high
